"""initial schema

Revision ID: d2c6b7a90b48
Revises:
Create Date: 2026-10-06 10:01:41.353583
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d2c6b7a90b48"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recorder_blobs",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "recorder_events",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id", "seq"),
        sa.UniqueConstraint("event_hash", name="uq_recorder_event_hash"),
    )
    op.create_table(
        "paypal_requests",
        sa.Column("operation_key", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("app_label", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("resource_status", sa.String(length=64), nullable=True),
        sa.Column("debug_id", sa.String(length=64), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("operation_key"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("app_label", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("transmission_id", sa.String(length=64), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "mandate_nonces",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "nonce"),
    )
    op.create_table(
        "vault_addresses",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("ref", sa.String(length=64), nullable=False),
        sa.Column("address_json", sa.Text(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "ref"),
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_usage_at"), "llm_usage", ["at"], unique=False)
    op.create_index(op.f("ix_llm_usage_model"), "llm_usage", ["model"], unique=False)
    op.create_table(
        "llm_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_table(
        "reconcile_tracked",
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("app", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("final", sa.Integer(), nullable=False),
        sa.Column("polls", sa.Integer(), nullable=False),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reconcile_tracked")
    op.drop_table("llm_cache")
    op.drop_index(op.f("ix_llm_usage_model"), table_name="llm_usage")
    op.drop_index(op.f("ix_llm_usage_at"), table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_table("vault_addresses")
    op.drop_table("mandate_nonces")
    op.drop_table("webhook_events")
    op.drop_table("paypal_requests")
    op.drop_table("recorder_events")
    op.drop_table("recorder_blobs")
    # ### end Alembic commands ###
